version: '3'

services:
  shop:
    container_name: shop-tp24-nl
    image: dockware/flex:latest
    ports:
      - "3003:80"     # apache2
    volumes:
      - "./src/custom/plugins:/var/www/html/custom/plugins"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0  
      - FILEBEAT_ENABLED=0


## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false